name: Release Drafter

on:
  push:
    branches:
      - add/release_notes

jobs:
  update_release_draft:
    if: github.repository == 'saimedhi/dashboards-flow-framework'
    name: Update draft release notes
    runs-on: ubuntu-latest
    steps:
      - name: Update draft release notes
        uses: release-drafter/release-drafter@v5
        with:
          config-name: draft-release-notes-config.yml
          name: Version (set here)
          tag: (None)
          
